name: ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - pip
  - pip:
     - dvc==3.60.1
     - poetry==2.2.1
     - pre-commit==4.3.0
     - poetry-plugin-export==1.9.0
     - uvicorn==0.38.0
     - gunicorn==22.0.0
     - pandas==2.3.3
     - numpy==2.3.4
     - ipykernel==7.1.0
     - hydra-core==1.3.2
     - black==25.9.0
     - isort==7.0.0
     - scikit-learn==1.7.2
     - joblib==1.5.2